### IMPORT LIBRARY

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### LOAD DATASET

In [3]:
df = pd.read_csv('customerData_500k.csv')
df.head()

,CustomerID,Age,AnnualIncome,NumberOfPurchases,TimeSpentOnWebsite,CustomerTenureYears,LastPurchaseDaysAgo,Gender,ProductCategory,PreferredDevice,Region,ReferralSource,CustomerSegment,LoyaltyProgram,DiscountsAvailed,SessionCount,CustomerSatisfaction,PurchaseStatus,PromoCode
0,CUST1000000,37.0,57722.572411,19,5.908826,1.093430,11,M,Furniture,Desktop,South,Paid Ads,Regular,1,5,3,2,1,SAVE10
1,CUST1000001,63.0,21328.925876,10,6.970749,0.649246,20,Female,Furniture,Mobile,East,Organic,VIP,0,4,2,3,0,FREESHIP
2,CUST1000002,60.0,150537.742465,19,35.004954,3.858211,25,Male,Electronics,Desktop,South,Organic,VIP,1,2,5,2,0,NONE
3,CUST1000003,19.0,63508.762549,10,14.818000,7.554374,20,Male,Furniture,Desktop,West,Paid Ads,Premium,0,0,1,3,0,NONE
4,CUST1000004,54.0,100399.558368,19,55.925462,0.197411,92,Male,Electronics,Mobile,SOUTH,Referral,Regular,1,4,1,2,0,NONE

### DATA UNDERSTANDING

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502500 entries, 0 to 502499
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CustomerID            502500 non-null  object
 1   Age                   487417 non-null  float64
 2   AnnualIncome          487486 non-null  float64
 3   NumberOfPurchases     502500 non-null  int64
 4   TimeSpentOnWebsite    502500 non-null  float64
 5   CustomerTenureYears   502500 non-null  float64
 6   LastPurchaseDaysAgo   502500 non-null  int64
 7   Gender                487419 non-null  object
 8   ProductCategory       502500 non-null  object
 9   PreferredDevice       502500 non-null  object
 10  Region                487425 non-null  object
 11  ReferralSource        502500 non-null  object
 12  CustomerSegment       502500 non-null  object
 13  LoyaltyProgram        502500 non-null  int64
 14  DiscountsAvailed      502500 non-null  int64
 15  SessionCount          502500 non-null  int64
 16  CustomerSatisfaction  502500 non-null  int64
 17  PurchaseStatus        502500 non-null  int64
 18  PromoCode             502500 non-null  object
dtypes: float64(4), int64(7), object(8)
memory usage: 72.8+ MB

In [5]:
df.columns

Index(['CustomerID', 'Age', 'AnnualIncome', 'NumberOfPurchases',
       'TimeSpentOnWebsite', 'CustomerTenureYears', 'LastPurchaseDaysAgo',
       'Gender', 'ProductCategory', 'PreferredDevice', 'Region',
       'ReferralSource', 'CustomerSegment', 'LoyaltyProgram',
       'DiscountsAvailed', 'SessionCount', 'CustomerSatisfaction',
       'PurchaseStatus', 'PromoCode'],
      dtype='object')

In [6]:
df.describe()

,Age,AnnualIncome,NumberOfPurchases,TimeSpentOnWebsite,CustomerTenureYears,LastPurchaseDaysAgo,LoyaltyProgram,DiscountsAvailed,SessionCount,CustomerSatisfaction,PurchaseStatus
count,487417.000000,4.874860e+05,502500.000000,502500.000000,502500.000000,502500.000000,502500.000000,502500.000000,502500.000000,502500.000000,502500.000000
mean,43.932799,8.861056e+04,11.387751,32.311521,2.163232,60.186953,0.501146,3.154740,2.702300,3.219628,0.418352
std,15.754045,6.560326e+04,6.000875,31.243341,2.197367,54.885166,0.499999,1.879326,5.513613,0.826430,0.493289
min,15.000000,1.196639e+04,-1.000000,-3.804161,-0.418429,-11.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,30.000000,5.214040e+04,6.000000,15.921025,0.591980,16.000000,0.000000,2.000000,1.000000,3.000000,0.000000
50%,44.000000,8.406014e+04,12.000000,30.911393,1.465732,31.000000,1.000000,3.000000,2.000000,3.000000,0.000000
75%,57.000000,1.170428e+05,16.000000,45.242071,3.009295,105.000000,1.000000,5.000000,3.000000,4.000000,1.000000
max,81.000000,1.199910e+06,28.000000,599.890350,15.346356,189.000000,1.000000,10.000000,119.000000,5.000000,1.000000

In [7]:
df.isnull().sum()

CustomerID                  0
Age                     15083
AnnualIncome            15014
NumberOfPurchases           0
TimeSpentOnWebsite          0
CustomerTenureYears         0
LastPurchaseDaysAgo         0
Gender                  15081
ProductCategory             0
PreferredDevice             0
Region                  15075
ReferralSource              0
CustomerSegment             0
LoyaltyProgram              0
DiscountsAvailed            0
SessionCount                0
CustomerSatisfaction        0
PurchaseStatus              0
PromoCode                   0
dtype: int64

In [8]:
df.shape

(502500, 19)

In [9]:
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing (%)': missing_pct
}).sort_values('Missing (%)', ascending=False)
print(missing_df[missing_df['Missing Count'] > 0])

              Missing Count  Missing (%)
Age                   15083     3.001592
Gender                15081     3.001194
Region                15075     3.000000
AnnualIncome          15014     2.987861

In [10]:
df.duplicated().sum()

np.int64(2500)